import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope } from '@fortawesome/free-solid-svg-icons'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} >
        <div className="main p-5 gap-4 py-12">
          <div className="main-heading">
            <p className="color-heading-white">Let’s Get</p>
            <p className="color-heading-yellow">Started</p>
          </div>


          <p className="text-gray-300">
            Create an account or login to begin adventure
          </p>
          <div className='flex flex-col gap-5 my-3'>
            <div className="login-buttons">
              <button type="button" className="button bg-white w-full py-4 
            rounded-lg flex justify-center items-center text-md font-bold gap-2">
                <span className="button__icon text-lg">
                  {/* <ion-icon name="phone-portrait-outline"></ion-icon> */}
                  <FontAwesomeIcon icon={faEnvelope} />
                </span>
                <span className="button__text">Continue with phone</span>
              </button>

            </div>
            <div className="login-buttons">
              <button type="button" className="button bg-white w-full py-4 
            rounded-lg flex justify-center items-center text-md font-bold gap-2">
                <span className="button__icon text-lg">
                  <ion-icon name="logo-facebook"></ion-icon>
                </span>
                <span className="button__text">Continue with facebook</span>
              </button>
            </div>
            <div className="login-buttons">
              <button type="button" className="button bg-white w-full py-4 
            rounded-lg flex justify-center items-center text-md font-bold gap-2">
                <span className="button__icon text-lg">
                  <ion-icon name="logo-google"></ion-icon>
                </span>
                <span className="button__text">Continue with Google</span>
              </button>
            </div>
          </div>

          <p className='text-white text-sm mx-auto'>
            Already have an account? Login
          </p>
        </div>
      </main>
    </>
  )
}
